### ISSUE TITLE
Installation instructions update

### ISSUE THREAD

**Issue by Briguy52** [akullpp/karma-cucumber-reporter#1]
Hey, first off, this library is awesome, and I really appreciate you sharing it. Just wanted to let you know that I had to add this `require` line to my `karma.conf.js` in order to get it to work—maybe this goes into the README?

The error I got without this line:
```
 10% building modules 1/1 modules 0 active11 04 2019 10:30:06.330:ERROR [reporter]: Can not load reporter "cucumber", it is not registered!
```

`require` line I added:
```
    // karma.conf.js
    plugins: [
      ...
      require('karma-cucumber-reporter'),
    ],
```

**Comment by akullpp** [comment]
Thank's added it. :-)
